### ISSUE TITLE
Support for BigAutoField

### ISSUE THREAD

**Issue by raratiru** [jordaneremieff/djantic#23]
[`BigAutoField`](https://docs.djangoproject.com/en/dev/ref/models/fields/#bigautofield), is the default value of [`DEFAULT_AUTO_FIELD`](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-DEFAULT_AUTO_FIELD) for new [Django-3.2 projects](https://docs.djangoproject.com/en/dev/releases/3.2/#customizing-type-of-auto-created-primary-keys).

**Comment by jordaneremieff** [comment]
Added https://github.com/jordaneremieff/djantic/commit/859e2e5532c9147edccf0152465a8e66b602e10a
