### ISSUE TITLE
Unable to support more than Level 2 relations

### ISSUE THREAD

**Issue by faner-father** [jordaneremieff/djantic#24]
class Level1(models.Mode):
   name = models.CharField()
   
class Level2(models.Model):
  parent = models.ForeignKey(Level1)
   name2 = models.Charge()
   
  class Level3(models.Model):
  parent = models.ForeignKey(Level2)
   name3 = models.Charge()

   class Level3Schema(ModelSchema):
      name3: str = Field()
    
class Level2Schema(ModelSchema):
     level3_set:List[Level3Schema] = Field(None)
     name2: str = Field(None)
     
   class Level1Schema(ModelSchema):
       level2_set :List[Level2Schema] = Field(None)
       name1:str = Field(None)
       
       as following is not work:
     Level1Schema.from_django(level1_instance)

**Comment by jordaneremieff** [comment]
@faner-father I only glanced at this before, but looking a bit closer it's not very clear to me what you're trying to achieve. Could you update the ticket description with more details/complete example to demonstrate the issue?

**Comment by jordaneremieff** [comment]
I'm assuming the work done by @phbernardes in https://github.com/jordaneremieff/djantic/pull/52 will solve this.
