### ISSUE TITLE
ValueError: cannot specify both default and default_factory

### ISSUE THREAD

**Issue by mmcardle** [jordaneremieff/djantic#26]
Hello,

This is a great library. Looking to contribute if you are needing anything done.

Getting this error but I see it looks fixed in your `main` branch.

```
  File "\.venv\lib\site-packages\djantic\main.py", line 102, in __new__
    p_model = create_model(
  File "pydantic\main.py", line 990, in pydantic.main.create_model
  File ".venv\lib\site-packages\djantic\main.py", line 34, in __new__
    cls = super().__new__(mcs, name, bases, namespace)
  File "pydantic\main.py", line 299, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 403, in pydantic.fields.ModelField.infer
  File "pydantic\fields.py", line 388, in pydantic.fields.ModelField._get_field_info
  File "pydantic\fields.py", line 173, in pydantic.fields.FieldInfo._validate
ValueError: cannot specify both default and default_factory
```

```
Django==3.2.3
djantic==0.2.0
pydantic==1.8.2
```

So just posting this for tracking incase anyone else has the same issue.

**Comment by mmcardle** [comment]
Fix was to use

`pydantic ==1.7.4`

**Comment by jordaneremieff** [comment]
Hello @mmcardle, I have just pushed a new release 0.3.0 a few minutes ago to resolve this.

**Comment by jordaneremieff** [comment]
Closing this but please let me know if the issue persists either in the most recent version of pydantic or others (the one you specified I was able to run the tests against locally without issue). There is an open issue here https://github.com/jordaneremieff/djantic/issues/16 on determining specific version support that I need to resolve at some point. 

For the moment it is implied that Django 3.* is supported, though Pydantic is only tested against the most recent release. I'm less familiar with the Pydantic release cycles and pay more close attention to changes across Django releases day-to-day, so if you or anyone else have any insights into how to approach the Pydantic versioning specifically please comment in the versioning ticket any suggestions.

**Comment by mmcardle** [comment]
`v0.3` works for me to fix this issue 👍
