### ISSUE TITLE
Please add root_validator

### ISSUE THREAD

**Issue by 50Bytes-dev** [jordaneremieff/djantic#44]
@root_validator
    def _set_fields(cls, values: dict) -> dict:
        DON'T WORK

**Comment by 50Bytes-dev** [comment]
I have PlacedSchema and in this PlacedSchema list of OrderSchema, on serialization OrderSchema validator don't work

**Comment by jordaneremieff** [comment]
Hi @50Bytes-dev, could you post an example of Django models and Djantic schemas that I can use to reproduce your issue to investigate?

**Comment by jordaneremieff** [comment]
Closing this until more info is provided.
